### ISSUE TITLE
Uno support: according to JMRI devs it should work

### ISSUE THREAD

**Issue by k4kfh** [madleech/ArduinoCMRI#3]
I know the README says the Uno won't work because JMRI leaves both DTR and RTS off. However, in a conversation with the JMRI developers, I have been informed this is not the case. Does this mean the Uno should work? Perhaps you should update your README...

[Conversation I had with JMRI devs](https://github.com/JMRI/JMRI/issues/259)

**Comment by k4kfh** [comment]
# Update
I tested the "Hello World" example with the Uno this evening, just using the LED built into the board and setting it up as a Light in JMRI. I can confirm it works. I did not test any input systems, but I am assuming those work too. Please update the README that Uno/other non-FTDI boards work.

**Comment by madleech** [comment]
Thanks very much for looking in to this. I don't actually have a UNO and instead was using a serial port sniffer to see exactly what was going on. I'll update the readme and remove that note, but will keep it as a troubleshooting step.

**Comment by k4kfh** [comment]
No probem, glad it worked out as true FTDI Arduinos are much harder to find now.

You may also want to check your example programs one more time. I don't remember off the top of my head exactly what the error was, but the hello_world example in ``/examples`` actually had a compilation error for me. The one in ``README.md`` worked fine though, so I'm not sure what's up with that. Awesome library though!

**Comment by madleech** [comment]
All fixed. The compilation errors might have been from #5? The example program compiled perfectly for me today.
